Update ci_html_build.yml

diff --git a/.github/workflows/ci_html_build.yml b/.github/workflows/ci_html_build.yml
--- a/.github/workflows/ci_html_build.yml
+++ b/.github/workflows/ci_html_build.yml
@@ -53,9 +53,33 @@ jobs:
           fi
           pip install notebook
           jupyter nbconvert --to notebook --execute --inplace "$notebook" 
-          git add "$notebook"
-          git commit -m "Execute notebooks"
-          git push origin HEAD:gh-storage --force
+
+      - name: Commit modified file on current branch
+        run: |
+          git config user.name 'CI Bot'
+          git config user.email 'action@github.com'
+          git add "$notebook" 
+          git commit -m "Storing executed notebook $notebook"
+
+      - name: Checkout only the file to the target branch
+        run: |
+          git checkout -f gh-storage
+          git checkout @{-1} "$notebook" 
+
+      - name: Commit and push modifications to target branch
+        run: |
+          git commit -m "Storing executed notebook $notebook"
+
+          MAX_RETRIES=5
+          RETRY_DELAY=10s
+          for i in $(seq 1 $MAX_RETRIES); do
+            git push origin gh-storage --force && break || {
+              echo "Push $i failed... waiting $RETRY_DELAY"
+              sleep $RETRY_DELAY
+            }
+          done
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
 
   generate_html:
